### ISSUE TITLE
Addition of Tucson Rain files

### ISSUE THREAD

**Issue by kaiiam** [jkhonan/502#3]
@jkhonan it's good to see you took the initiative to add the https://github.com/jkhonan/502/blob/master/Tucson%20Rain and https://github.com/jkhonan/502/blob/master/tucson_rain.csv files, however, I think in order to make for a more comprehensive project, I think it would be stronger to generate this kind of file using Dr. Haiquan's `rainlog_ex.py` file. In that we could modify it to give us data of a particular range (e.g. 2015-2020) or whatever, and use the same range for the flagstaff data. 

One way we could make this stronger would not be to have two separate python files and hardcode the coordinates for Tucson and Flagstaff into them. Instead we could have the script take arguments of the 4 coordinates. Then in a speperate bash script, we could call it twice, specifying the "Tucson" and "Flagstaff" coordinates and outputting each data file. Let me know @jkhonan what you think.

**Comment by jkhonan** [comment]
I think having one working file would be easiest as well.

**Comment by kaiiam** [comment]
@jkhonan sounds good let's have that be our first objective. It looks like https://github.com/jkhonan/502/blob/master/rain_data_retrieval_flagstaff.py is based on Dr. Haiquan's version. Did you make any other changes? 

Another thing we can do is having our own development branches (but I'm not sure how to do that super easily using branching), so perhaps it's easiest to just have one person make changes at a time.

**Comment by jkhonan** [comment]
@kaiiam Here is where I grabbed the base code: https://github.com/Rainlog/rainlog-api/blob/master/python/rainlog.py
This is the same as the code that Haiquan posted in D2L.

I added the coordinates, but other than that I think I reset the rest of the changes I made because they didn't work. So this should be the same as what is in the link, just with the addition of flag coordinates.

I'm happy to make changes instead of branching off. I think keeping it simple is better for me at this point. 

PS sorry you got stuck with me in your group! haha. I feel like I've learned a ridiculous amount in this class, but mostly I've learned that I need to take way more coding classes...

**Comment by kaiiam** [comment]
@jkhonan 

> I added the coordinates, but other than that I think I reset the rest of the changes I made because they didn't work. So this should be the same as what is in the link, just with the addition of flag coordinates.

sounds good better to start with something clean that we know "should work". I'll try to add command line arguments to this file which take in the 4 coordinates. 

> I'm happy to make changes instead of branching off. I think keeping it simple is better for me at this point.

agreed lets just be smart about who edits what file when. I think if we are all working of different files it will be easier. 

> PS sorry you got stuck with me in your group! haha. I feel like I've learned a ridiculous amount in this class, but mostly I've learned that I need to take way more coding classes...

Don't say that you're doing great!!!! This is how we learn by doing and giving and receiving feedback.
